### ISSUE TITLE
Menu collapse on click

### ISSUE THREAD

**Issue by panev** [dgiormov/ista.agenda.builder.web#3]
When you expand the menu and click on a menu item or outside of it, it stays open / doesn't collapse back. 

We should close the menu when the user clicks on an item or outside of it.

**Comment by dgiormov** [comment]
fixed, reopen if issues occur.

**Comment by dgiormov** [comment]
I have closed the wrong issue:)

**Comment by fen4o** [comment]
Fixed in 1039852ff15fe9d7b6eeb16b8d7803d5e09c82f5

**Comment by panev** [comment]
I've noticed that this issue remains when you've expanded the menu and you click on the ista logo/home button: the menu doesn't close.
